# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ControlProgramForm.ui'
#
# Created: Sat Jun 04 18:52:00 2016
#      by: PyQt4 UI code generator 4.11.3
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName(_fromUtf8("MainWindow"))
        MainWindow.resize(971, 603)
        self.centralwidget = QtGui.QWidget(MainWindow)
        self.centralwidget.setObjectName(_fromUtf8("centralwidget"))
        self.gridLayout_2 = QtGui.QGridLayout(self.centralwidget)
        self.gridLayout_2.setObjectName(_fromUtf8("gridLayout_2"))
        self.panel_for_manual_sending_of_commands_label = QtGui.QLabel(self.centralwidget)
        self.panel_for_manual_sending_of_commands_label.setStyleSheet(_fromUtf8("font: 75 15pt \"Ubuntu\";"))
        self.panel_for_manual_sending_of_commands_label.setTextFormat(QtCore.Qt.PlainText)
        self.panel_for_manual_sending_of_commands_label.setObjectName(_fromUtf8("panel_for_manual_sending_of_commands_label"))
        self.gridLayout_2.addWidget(self.panel_for_manual_sending_of_commands_label, 2, 0, 1, 1)
        self.undecoded_packages_textEdit = QtGui.QTextEdit(self.centralwidget)
        self.undecoded_packages_textEdit.setStyleSheet(_fromUtf8("background-color: qlineargradient(spread:reflect, x1:0.038, y1:0.517045, x2:1, y2:0.511, stop:0.402844 rgba(255, 255, 255, 254), stop:1 rgba(174, 151, 255, 255));"))
        self.undecoded_packages_textEdit.setObjectName(_fromUtf8("undecoded_packages_textEdit"))
        self.gridLayout_2.addWidget(self.undecoded_packages_textEdit, 1, 0, 1, 1)
        self.undecoded_data_from_packages_label = QtGui.QLabel(self.centralwidget)
        self.undecoded_data_from_packages_label.setStyleSheet(_fromUtf8("font: 75 15pt \"Ubuntu\";"))
        self.undecoded_data_from_packages_label.setObjectName(_fromUtf8("undecoded_data_from_packages_label"))
        self.gridLayout_2.addWidget(self.undecoded_data_from_packages_label, 0, 0, 1, 1)
        self.modes_of_operation_tabWidget = QtGui.QTabWidget(self.centralwidget)
        self.modes_of_operation_tabWidget.setMinimumSize(QtCore.QSize(0, 50))
        self.modes_of_operation_tabWidget.setStyleSheet(_fromUtf8("font: 75 12pt \"Ubuntu\";"))
        self.modes_of_operation_tabWidget.setTabPosition(QtGui.QTabWidget.North)
        self.modes_of_operation_tabWidget.setTabShape(QtGui.QTabWidget.Rounded)
        self.modes_of_operation_tabWidget.setElideMode(QtCore.Qt.ElideNone)
        self.modes_of_operation_tabWidget.setDocumentMode(True)
        self.modes_of_operation_tabWidget.setTabsClosable(False)
        self.modes_of_operation_tabWidget.setMovable(False)
        self.modes_of_operation_tabWidget.setObjectName(_fromUtf8("modes_of_operation_tabWidget"))
        self.modes_of_operation_tab = QtGui.QWidget()
        self.modes_of_operation_tab.setObjectName(_fromUtf8("modes_of_operation_tab"))
        self.formLayout_2 = QtGui.QFormLayout(self.modes_of_operation_tab)
        self.formLayout_2.setFieldGrowthPolicy(QtGui.QFormLayout.AllNonFixedFieldsGrow)
        self.formLayout_2.setObjectName(_fromUtf8("formLayout_2"))
        self.modes_choosing_of_the_operation_mode_gridLayout = QtGui.QGridLayout()
        self.modes_choosing_of_the_operation_mode_gridLayout.setObjectName(_fromUtf8("modes_choosing_of_the_operation_mode_gridLayout"))
        self.enable_nominal_mode_pushButton = QtGui.QPushButton(self.modes_of_operation_tab)
        self.enable_nominal_mode_pushButton.setObjectName(_fromUtf8("enable_nominal_mode_pushButton"))
        self.modes_choosing_of_the_operation_mode_gridLayout.addWidget(self.enable_nominal_mode_pushButton, 2, 1, 1, 1)
        self.enable_operating_mode_label = QtGui.QLabel(self.modes_of_operation_tab)
        self.enable_operating_mode_label.setObjectName(_fromUtf8("enable_operating_mode_label"))
        self.modes_choosing_of_the_operation_mode_gridLayout.addWidget(self.enable_operating_mode_label, 3, 0, 1, 1)
        self.enable_operating_mode_pushButton = QtGui.QPushButton(self.modes_of_operation_tab)
        self.enable_operating_mode_pushButton.setObjectName(_fromUtf8("enable_operating_mode_pushButton"))
        self.modes_choosing_of_the_operation_mode_gridLayout.addWidget(self.enable_operating_mode_pushButton, 3, 1, 1, 1)
        self.enable_emergency_mode_pushButton = QtGui.QPushButton(self.modes_of_operation_tab)
        self.enable_emergency_mode_pushButton.setObjectName(_fromUtf8("enable_emergency_mode_pushButton"))
        self.modes_choosing_of_the_operation_mode_gridLayout.addWidget(self.enable_emergency_mode_pushButton, 0, 1, 1, 1)
        self.enable_emergency_mode_label = QtGui.QLabel(self.modes_of_operation_tab)
        self.enable_emergency_mode_label.setObjectName(_fromUtf8("enable_emergency_mode_label"))
        self.modes_choosing_of_the_operation_mode_gridLayout.addWidget(self.enable_emergency_mode_label, 0, 0, 1, 1)
        self.enable_nominal_mode_label = QtGui.QLabel(self.modes_of_operation_tab)
        self.enable_nominal_mode_label.setObjectName(_fromUtf8("enable_nominal_mode_label"))
        self.modes_choosing_of_the_operation_mode_gridLayout.addWidget(self.enable_nominal_mode_label, 2, 0, 1, 1)
        self.enable_minimal_mode_label = QtGui.QLabel(self.modes_of_operation_tab)
        self.enable_minimal_mode_label.setObjectName(_fromUtf8("enable_minimal_mode_label"))
        self.modes_choosing_of_the_operation_mode_gridLayout.addWidget(self.enable_minimal_mode_label, 1, 0, 1, 1)
        self.enable_minimal_mode_pushButton = QtGui.QPushButton(self.modes_of_operation_tab)
        self.enable_minimal_mode_pushButton.setObjectName(_fromUtf8("enable_minimal_mode_pushButton"))
        self.modes_choosing_of_the_operation_mode_gridLayout.addWidget(self.enable_minimal_mode_pushButton, 1, 1, 1, 1)
        self.formLayout_2.setLayout(0, QtGui.QFormLayout.LabelRole, self.modes_choosing_of_the_operation_mode_gridLayout)
        self.modes_of_operation_tabWidget.addTab(self.modes_of_operation_tab, _fromUtf8(""))
        self.other_commands_tab = QtGui.QWidget()
        self.other_commands_tab.setObjectName(_fromUtf8("other_commands_tab"))
        self.formLayout = QtGui.QFormLayout(self.other_commands_tab)
        self.formLayout.setFieldGrowthPolicy(QtGui.QFormLayout.AllNonFixedFieldsGrow)
        self.formLayout.setObjectName(_fromUtf8("formLayout"))
        self.radio_module_settings_gridLayout = QtGui.QGridLayout()
        self.radio_module_settings_gridLayout.setObjectName(_fromUtf8("radio_module_settings_gridLayout"))
        self.set_channel_number_comboBox = QtGui.QComboBox(self.other_commands_tab)
        self.set_channel_number_comboBox.setObjectName(_fromUtf8("set_channel_number_comboBox"))
        self.set_channel_number_comboBox.addItem(_fromUtf8(""))
        self.set_channel_number_comboBox.addItem(_fromUtf8(""))
        self.set_channel_number_comboBox.addItem(_fromUtf8(""))
        self.set_channel_number_comboBox.addItem(_fromUtf8(""))
        self.set_channel_number_comboBox.addItem(_fromUtf8(""))
        self.set_channel_number_comboBox.addItem(_fromUtf8(""))
        self.set_channel_number_comboBox.addItem(_fromUtf8(""))
        self.set_channel_number_comboBox.addItem(_fromUtf8(""))
        self.set_channel_number_comboBox.addItem(_fromUtf8(""))
        self.set_channel_number_comboBox.addItem(_fromUtf8(""))
        self.set_channel_number_comboBox.addItem(_fromUtf8(""))
        self.set_channel_number_comboBox.addItem(_fromUtf8(""))
        self.set_channel_number_comboBox.addItem(_fromUtf8(""))
        self.set_channel_number_comboBox.addItem(_fromUtf8(""))
        self.set_channel_number_comboBox.addItem(_fromUtf8(""))
        self.set_channel_number_comboBox.addItem(_fromUtf8(""))
        self.radio_module_settings_gridLayout.addWidget(self.set_channel_number_comboBox, 2, 1, 1, 1)
        self.set_channel_number_pushButton = QtGui.QPushButton(self.other_commands_tab)
        self.set_channel_number_pushButton.setObjectName(_fromUtf8("set_channel_number_pushButton"))
        self.radio_module_settings_gridLayout.addWidget(self.set_channel_number_pushButton, 2, 2, 1, 1)
        self.toggle_transmission_pushButton = QtGui.QPushButton(self.other_commands_tab)
        self.toggle_transmission_pushButton.setObjectName(_fromUtf8("toggle_transmission_pushButton"))
        self.radio_module_settings_gridLayout.addWidget(self.toggle_transmission_pushButton, 1, 2, 1, 1)
        self.radio_module_settings_label = QtGui.QLabel(self.other_commands_tab)
        self.radio_module_settings_label.setStyleSheet(_fromUtf8("font: 75 15pt \"Ubuntu\";"))
        self.radio_module_settings_label.setObjectName(_fromUtf8("radio_module_settings_label"))
        self.radio_module_settings_gridLayout.addWidget(self.radio_module_settings_label, 0, 0, 1, 1)
        self.toggle_transmission_comboBox = QtGui.QComboBox(self.other_commands_tab)
        self.toggle_transmission_comboBox.setObjectName(_fromUtf8("toggle_transmission_comboBox"))
        self.toggle_transmission_comboBox.addItem(_fromUtf8(""))
        self.toggle_transmission_comboBox.addItem(_fromUtf8(""))
        self.radio_module_settings_gridLayout.addWidget(self.toggle_transmission_comboBox, 1, 1, 1, 1)
        self.set_channel_number_label = QtGui.QLabel(self.other_commands_tab)
        self.set_channel_number_label.setObjectName(_fromUtf8("set_channel_number_label"))
        self.radio_module_settings_gridLayout.addWidget(self.set_channel_number_label, 2, 0, 1, 1)
        self.toggle_transmission_label = QtGui.QLabel(self.other_commands_tab)
        self.toggle_transmission_label.setObjectName(_fromUtf8("toggle_transmission_label"))
        self.radio_module_settings_gridLayout.addWidget(self.toggle_transmission_label, 1, 0, 1, 1)
        self.formLayout.setLayout(0, QtGui.QFormLayout.LabelRole, self.radio_module_settings_gridLayout)
        self.separation_label = QtGui.QLabel(self.other_commands_tab)
        self.separation_label.setText(_fromUtf8(""))
        self.separation_label.setObjectName(_fromUtf8("separation_label"))
        self.formLayout.setWidget(2, QtGui.QFormLayout.LabelRole, self.separation_label)
        self.real_time_clock_settings_gridLayout = QtGui.QGridLayout()
        self.real_time_clock_settings_gridLayout.setObjectName(_fromUtf8("real_time_clock_settings_gridLayout"))
        self.real_time_clock_settings_pushButton = QtGui.QPushButton(self.other_commands_tab)
        self.real_time_clock_settings_pushButton.setObjectName(_fromUtf8("real_time_clock_settings_pushButton"))
        self.real_time_clock_settings_gridLayout.addWidget(self.real_time_clock_settings_pushButton, 2, 1, 1, 1)
        self.real_time_clock_settings_dateTimeEdit = QtGui.QDateTimeEdit(self.other_commands_tab)
        self.real_time_clock_settings_dateTimeEdit.setObjectName(_fromUtf8("real_time_clock_settings_dateTimeEdit"))
        self.real_time_clock_settings_gridLayout.addWidget(self.real_time_clock_settings_dateTimeEdit, 2, 0, 1, 1)
        self.other_commands_real_time_clock_settings_label = QtGui.QLabel(self.other_commands_tab)
        self.other_commands_real_time_clock_settings_label.setStyleSheet(_fromUtf8("font: 75 15pt \"Ubuntu\";"))
        self.other_commands_real_time_clock_settings_label.setObjectName(_fromUtf8("other_commands_real_time_clock_settings_label"))
        self.real_time_clock_settings_gridLayout.addWidget(self.other_commands_real_time_clock_settings_label, 1, 0, 1, 1)
        self.formLayout.setLayout(1, QtGui.QFormLayout.LabelRole, self.real_time_clock_settings_gridLayout)
        self.modes_of_operation_tabWidget.addTab(self.other_commands_tab, _fromUtf8(""))
        self.gridLayout_2.addWidget(self.modes_of_operation_tabWidget, 4, 0, 1, 1)
        self.command_eval_date_time_gridLayout = QtGui.QGridLayout()
        self.command_eval_date_time_gridLayout.setObjectName(_fromUtf8("command_eval_date_time_gridLayout"))
        self.command_eval_date_time_dateTimeEdit = QtGui.QDateTimeEdit(self.centralwidget)
        self.command_eval_date_time_dateTimeEdit.setObjectName(_fromUtf8("command_eval_date_time_dateTimeEdit"))
        self.command_eval_date_time_gridLayout.addWidget(self.command_eval_date_time_dateTimeEdit, 1, 0, 1, 1)
        self.command_eval_date_time_checkBox = QtGui.QCheckBox(self.centralwidget)
        self.command_eval_date_time_checkBox.setObjectName(_fromUtf8("command_eval_date_time_checkBox"))
        self.command_eval_date_time_gridLayout.addWidget(self.command_eval_date_time_checkBox, 1, 1, 1, 1)
        self.command_eval_date_time_label = QtGui.QLabel(self.centralwidget)
        self.command_eval_date_time_label.setObjectName(_fromUtf8("command_eval_date_time_label"))
        self.command_eval_date_time_gridLayout.addWidget(self.command_eval_date_time_label, 0, 0, 1, 2)
        self.gridLayout_2.addLayout(self.command_eval_date_time_gridLayout, 3, 0, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)
        self.actionOpen = QtGui.QAction(MainWindow)
        self.actionOpen.setEnabled(True)
        self.actionOpen.setObjectName(_fromUtf8("actionOpen"))
        self.actionSave = QtGui.QAction(MainWindow)
        self.actionSave.setObjectName(_fromUtf8("actionSave"))
        self.actionClose = QtGui.QAction(MainWindow)
        self.actionClose.setObjectName(_fromUtf8("actionClose"))

        self.retranslateUi(MainWindow)
        self.modes_of_operation_tabWidget.setCurrentIndex(1)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(_translate("MainWindow", "Satellite simulator control program", None))
        self.panel_for_manual_sending_of_commands_label.setText(_translate("MainWindow", "Панель посыла команд в ручном режиме:", None))
        self.undecoded_data_from_packages_label.setText(_translate("MainWindow", "Панель отображения содержимого ответных пакетов:", None))
        self.enable_nominal_mode_pushButton.setText(_translate("MainWindow", "Отправить", None))
        self.enable_operating_mode_label.setText(_translate("MainWindow", "Перейти в режим работы с научной аппаратурой ", None))
        self.enable_operating_mode_pushButton.setText(_translate("MainWindow", "Отправить", None))
        self.enable_emergency_mode_pushButton.setText(_translate("MainWindow", "Отправить", None))
        self.enable_emergency_mode_label.setText(_translate("MainWindow", "Перейти в аварийный режим работы", None))
        self.enable_nominal_mode_label.setText(_translate("MainWindow", "Перейти в штатный режим работы", None))
        self.enable_minimal_mode_label.setText(_translate("MainWindow", "Перейти в режим работы с минимальным энергопотреблением ", None))
        self.enable_minimal_mode_pushButton.setText(_translate("MainWindow", "Отправить", None))
        self.modes_of_operation_tabWidget.setTabText(self.modes_of_operation_tabWidget.indexOf(self.modes_of_operation_tab), _translate("MainWindow", "Переключение режимов работы спутника", None))
        self.set_channel_number_comboBox.setItemText(0, _translate("MainWindow", "1)   433.15 - 433.25  MHz", None))
        self.set_channel_number_comboBox.setItemText(1, _translate("MainWindow", "2)   433.25 - 433.35  MHz", None))
        self.set_channel_number_comboBox.setItemText(2, _translate("MainWindow", "3)   433.25 - 433.35  MHz", None))
        self.set_channel_number_comboBox.setItemText(3, _translate("MainWindow", "4)   433.45 - 433.55 MHz", None))
        self.set_channel_number_comboBox.setItemText(4, _translate("MainWindow", "5)   433.55 - 433.65 MHz", None))
        self.set_channel_number_comboBox.setItemText(5, _translate("MainWindow", "6)   433.65 - 433.75 MHz", None))
        self.set_channel_number_comboBox.setItemText(6, _translate("MainWindow", "7)   433.75 - 433.85 MHz", None))
        self.set_channel_number_comboBox.setItemText(7, _translate("MainWindow", "8)   433.85 - 433.95 MHz", None))
        self.set_channel_number_comboBox.setItemText(8, _translate("MainWindow", "9)   433.95 - 434.05 MHz", None))
        self.set_channel_number_comboBox.setItemText(9, _translate("MainWindow", "10) 434.05 - 434.15 MHz", None))
        self.set_channel_number_comboBox.setItemText(10, _translate("MainWindow", "11) 434.15 - 434.25 MHz", None))
        self.set_channel_number_comboBox.setItemText(11, _translate("MainWindow", "12) 434.25 - 434.35 MHz", None))
        self.set_channel_number_comboBox.setItemText(12, _translate("MainWindow", "13) 434.35 - 434.45 MHz", None))
        self.set_channel_number_comboBox.setItemText(13, _translate("MainWindow", "14) 434.45 - 434.55 MHz", None))
        self.set_channel_number_comboBox.setItemText(14, _translate("MainWindow", "15) 434.55 - 434.65 MHz", None))
        self.set_channel_number_comboBox.setItemText(15, _translate("MainWindow", "16) 434.65 - 434.75 MHz", None))
        self.set_channel_number_pushButton.setText(_translate("MainWindow", "Отправить", None))
        self.toggle_transmission_pushButton.setText(_translate("MainWindow", "Отправить", None))
        self.radio_module_settings_label.setText(_translate("MainWindow", "Настройки радиомодуля: ", None))
        self.toggle_transmission_comboBox.setItemText(0, _translate("MainWindow", "Выключить", None))
        self.toggle_transmission_comboBox.setItemText(1, _translate("MainWindow", "Включить", None))
        self.set_channel_number_label.setText(_translate("MainWindow", "Установить канал", None))
        self.toggle_transmission_label.setText(_translate("MainWindow", "Вкл/Выкл вещание в эфир", None))
        self.real_time_clock_settings_pushButton.setText(_translate("MainWindow", "Отправить", None))
        self.other_commands_real_time_clock_settings_label.setText(_translate("MainWindow", " Установка даты и времени на имитаторе СМКА:", None))
        self.modes_of_operation_tabWidget.setTabText(self.modes_of_operation_tabWidget.indexOf(self.other_commands_tab), _translate("MainWindow", "Остальные команды", None))
        self.command_eval_date_time_checkBox.setText(_translate("MainWindow", "Выполнить команду сразу при получении", None))
        self.command_eval_date_time_label.setText(_translate("MainWindow", "Установить время и дату выполнения посылаемой команды или выполнить команду сразу при получении:", None))
        self.actionOpen.setText(_translate("MainWindow", "Open", None))
        self.actionSave.setText(_translate("MainWindow", "Save", None))
        self.actionClose.setText(_translate("MainWindow", "Close", None))

