# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ControlProgramForm.ui'
#
# Created: Mon Sep 12 15:53:21 2016
#      by: PyQt4 UI code generator 4.11.3
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName(_fromUtf8("MainWindow"))
        MainWindow.resize(608, 739)
        self.centralwidget = QtGui.QWidget(MainWindow)
        self.centralwidget.setObjectName(_fromUtf8("centralwidget"))
        self.gridLayout_2 = QtGui.QGridLayout(self.centralwidget)
        self.gridLayout_2.setObjectName(_fromUtf8("gridLayout_2"))
        self.execution_date_time_gridLayout = QtGui.QGridLayout()
        self.execution_date_time_gridLayout.setObjectName(_fromUtf8("execution_date_time_gridLayout"))
        self.execution_dateTimeEdit = QtGui.QDateTimeEdit(self.centralwidget)
        self.execution_dateTimeEdit.setDateTime(QtCore.QDateTime(QtCore.QDate(2016, 1, 1), QtCore.QTime(0, 0, 0)))
        self.execution_dateTimeEdit.setObjectName(_fromUtf8("execution_dateTimeEdit"))
        self.execution_date_time_gridLayout.addWidget(self.execution_dateTimeEdit, 1, 0, 1, 1)
        self.execution_date_time_checkBox = QtGui.QCheckBox(self.centralwidget)
        self.execution_date_time_checkBox.setObjectName(_fromUtf8("execution_date_time_checkBox"))
        self.execution_date_time_gridLayout.addWidget(self.execution_date_time_checkBox, 1, 1, 1, 1)
        self.execution_date_time_label = QtGui.QLabel(self.centralwidget)
        self.execution_date_time_label.setObjectName(_fromUtf8("execution_date_time_label"))
        self.execution_date_time_gridLayout.addWidget(self.execution_date_time_label, 0, 0, 1, 2)
        self.gridLayout_2.addLayout(self.execution_date_time_gridLayout, 3, 0, 1, 1)
        self.undecoded_data_from_packages_label = QtGui.QLabel(self.centralwidget)
        self.undecoded_data_from_packages_label.setStyleSheet(_fromUtf8("font: 75 15pt \"Ubuntu\";"))
        self.undecoded_data_from_packages_label.setObjectName(_fromUtf8("undecoded_data_from_packages_label"))
        self.gridLayout_2.addWidget(self.undecoded_data_from_packages_label, 0, 0, 1, 1)
        self.panel_for_manual_sending_of_commands_label = QtGui.QLabel(self.centralwidget)
        self.panel_for_manual_sending_of_commands_label.setStyleSheet(_fromUtf8("font: 75 15pt \"Ubuntu\";"))
        self.panel_for_manual_sending_of_commands_label.setTextFormat(QtCore.Qt.PlainText)
        self.panel_for_manual_sending_of_commands_label.setObjectName(_fromUtf8("panel_for_manual_sending_of_commands_label"))
        self.gridLayout_2.addWidget(self.panel_for_manual_sending_of_commands_label, 2, 0, 1, 1)
        self.modes_of_operation_tabWidget = QtGui.QTabWidget(self.centralwidget)
        self.modes_of_operation_tabWidget.setMinimumSize(QtCore.QSize(0, 50))
        self.modes_of_operation_tabWidget.setStyleSheet(_fromUtf8("font: 75 12pt \"Ubuntu\";"))
        self.modes_of_operation_tabWidget.setTabPosition(QtGui.QTabWidget.North)
        self.modes_of_operation_tabWidget.setTabShape(QtGui.QTabWidget.Rounded)
        self.modes_of_operation_tabWidget.setElideMode(QtCore.Qt.ElideNone)
        self.modes_of_operation_tabWidget.setDocumentMode(True)
        self.modes_of_operation_tabWidget.setTabsClosable(False)
        self.modes_of_operation_tabWidget.setMovable(False)
        self.modes_of_operation_tabWidget.setObjectName(_fromUtf8("modes_of_operation_tabWidget"))
        self.modes_of_operation_tab = QtGui.QWidget()
        self.modes_of_operation_tab.setObjectName(_fromUtf8("modes_of_operation_tab"))
        self.formLayout_2 = QtGui.QFormLayout(self.modes_of_operation_tab)
        self.formLayout_2.setFieldGrowthPolicy(QtGui.QFormLayout.AllNonFixedFieldsGrow)
        self.formLayout_2.setObjectName(_fromUtf8("formLayout_2"))
        self.modes_choosing_of_the_operation_mode_gridLayout = QtGui.QGridLayout()
        self.modes_choosing_of_the_operation_mode_gridLayout.setObjectName(_fromUtf8("modes_choosing_of_the_operation_mode_gridLayout"))
        self.enable_nominal_mode_pushButton = QtGui.QPushButton(self.modes_of_operation_tab)
        self.enable_nominal_mode_pushButton.setObjectName(_fromUtf8("enable_nominal_mode_pushButton"))
        self.modes_choosing_of_the_operation_mode_gridLayout.addWidget(self.enable_nominal_mode_pushButton, 1, 1, 1, 1)
        self.enable_operating_mode_label = QtGui.QLabel(self.modes_of_operation_tab)
        self.enable_operating_mode_label.setObjectName(_fromUtf8("enable_operating_mode_label"))
        self.modes_choosing_of_the_operation_mode_gridLayout.addWidget(self.enable_operating_mode_label, 2, 0, 1, 1)
        self.enable_operating_mode_pushButton = QtGui.QPushButton(self.modes_of_operation_tab)
        self.enable_operating_mode_pushButton.setObjectName(_fromUtf8("enable_operating_mode_pushButton"))
        self.modes_choosing_of_the_operation_mode_gridLayout.addWidget(self.enable_operating_mode_pushButton, 2, 1, 1, 1)
        self.enable_nominal_mode_label = QtGui.QLabel(self.modes_of_operation_tab)
        self.enable_nominal_mode_label.setObjectName(_fromUtf8("enable_nominal_mode_label"))
        self.modes_choosing_of_the_operation_mode_gridLayout.addWidget(self.enable_nominal_mode_label, 1, 0, 1, 1)
        self.enable_minimal_mode_label = QtGui.QLabel(self.modes_of_operation_tab)
        self.enable_minimal_mode_label.setObjectName(_fromUtf8("enable_minimal_mode_label"))
        self.modes_choosing_of_the_operation_mode_gridLayout.addWidget(self.enable_minimal_mode_label, 0, 0, 1, 1)
        self.enable_minimal_mode_pushButton = QtGui.QPushButton(self.modes_of_operation_tab)
        self.enable_minimal_mode_pushButton.setObjectName(_fromUtf8("enable_minimal_mode_pushButton"))
        self.modes_choosing_of_the_operation_mode_gridLayout.addWidget(self.enable_minimal_mode_pushButton, 0, 1, 1, 1)
        self.formLayout_2.setLayout(0, QtGui.QFormLayout.LabelRole, self.modes_choosing_of_the_operation_mode_gridLayout)
        self.modes_of_operation_tabWidget.addTab(self.modes_of_operation_tab, _fromUtf8(""))
        self.toggle_power_tab = QtGui.QWidget()
        self.toggle_power_tab.setObjectName(_fromUtf8("toggle_power_tab"))
        self.gridLayoutWidget = QtGui.QWidget(self.toggle_power_tab)
        self.gridLayoutWidget.setGeometry(QtCore.QRect(10, 10, 581, 269))
        self.gridLayoutWidget.setObjectName(_fromUtf8("gridLayoutWidget"))
        self.gridLayout = QtGui.QGridLayout(self.gridLayoutWidget)
        self.gridLayout.setMargin(0)
        self.gridLayout.setObjectName(_fromUtf8("gridLayout"))
        self.device_power_disable_pushButton = QtGui.QPushButton(self.gridLayoutWidget)
        self.device_power_disable_pushButton.setObjectName(_fromUtf8("device_power_disable_pushButton"))
        self.gridLayout.addWidget(self.device_power_disable_pushButton, 4, 2, 1, 1)
        self.command_name_lineEdit = QtGui.QLineEdit(self.gridLayoutWidget)
        self.command_name_lineEdit.setObjectName(_fromUtf8("command_name_lineEdit"))
        self.gridLayout.addWidget(self.command_name_lineEdit, 8, 0, 1, 1)
        self.label = QtGui.QLabel(self.gridLayoutWidget)
        self.label.setStyleSheet(_fromUtf8(""))
        self.label.setObjectName(_fromUtf8("label"))
        self.gridLayout.addWidget(self.label, 0, 0, 1, 1)
        self.device_power_enable_pushButton = QtGui.QPushButton(self.gridLayoutWidget)
        self.device_power_enable_pushButton.setObjectName(_fromUtf8("device_power_enable_pushButton"))
        self.gridLayout.addWidget(self.device_power_enable_pushButton, 4, 1, 1, 1)
        self.label_2 = QtGui.QLabel(self.gridLayoutWidget)
        self.label_2.setStyleSheet(_fromUtf8("font: 75 15pt \"Ubuntu\";"))
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.gridLayout.addWidget(self.label_2, 2, 0, 1, 1)
        self.label_3 = QtGui.QLabel(self.gridLayoutWidget)
        self.label_3.setStyleSheet(_fromUtf8("font: 75 15pt \"Ubuntu\";"))
        self.label_3.setObjectName(_fromUtf8("label_3"))
        self.gridLayout.addWidget(self.label_3, 5, 0, 1, 1)
        self.label_5 = QtGui.QLabel(self.gridLayoutWidget)
        self.label_5.setStyleSheet(_fromUtf8(""))
        self.label_5.setObjectName(_fromUtf8("label_5"))
        self.gridLayout.addWidget(self.label_5, 6, 0, 1, 1)
        self.device_id_comboBox = QtGui.QComboBox(self.gridLayoutWidget)
        self.device_id_comboBox.setEditable(True)
        self.device_id_comboBox.setObjectName(_fromUtf8("device_id_comboBox"))
        self.device_id_comboBox.addItem(_fromUtf8(""))
        self.device_id_comboBox.setItemText(0, _fromUtf8(""))
        self.device_id_comboBox.addItem(_fromUtf8(""))
        self.device_id_comboBox.addItem(_fromUtf8(""))
        self.device_id_comboBox.addItem(_fromUtf8(""))
        self.device_id_comboBox.addItem(_fromUtf8(""))
        self.device_id_comboBox.addItem(_fromUtf8(""))
        self.device_id_comboBox.addItem(_fromUtf8(""))
        self.device_id_comboBox.addItem(_fromUtf8(""))
        self.gridLayout.addWidget(self.device_id_comboBox, 1, 0, 1, 1)
        self.command_arg_lineEdit = QtGui.QLineEdit(self.gridLayoutWidget)
        self.command_arg_lineEdit.setObjectName(_fromUtf8("command_arg_lineEdit"))
        self.gridLayout.addWidget(self.command_arg_lineEdit, 8, 1, 1, 1)
        self.label_6 = QtGui.QLabel(self.gridLayoutWidget)
        self.label_6.setObjectName(_fromUtf8("label_6"))
        self.gridLayout.addWidget(self.label_6, 6, 1, 1, 1)
        self.device_command_pushButton = QtGui.QPushButton(self.gridLayoutWidget)
        self.device_command_pushButton.setObjectName(_fromUtf8("device_command_pushButton"))
        self.gridLayout.addWidget(self.device_command_pushButton, 8, 2, 1, 1)
        self.modes_of_operation_tabWidget.addTab(self.toggle_power_tab, _fromUtf8(""))
        self.other_commands_tab = QtGui.QWidget()
        self.other_commands_tab.setObjectName(_fromUtf8("other_commands_tab"))
        self.formLayout = QtGui.QFormLayout(self.other_commands_tab)
        self.formLayout.setFieldGrowthPolicy(QtGui.QFormLayout.AllNonFixedFieldsGrow)
        self.formLayout.setObjectName(_fromUtf8("formLayout"))
        self.radio_module_settings_gridLayout = QtGui.QGridLayout()
        self.radio_module_settings_gridLayout.setObjectName(_fromUtf8("radio_module_settings_gridLayout"))
        self.label_4 = QtGui.QLabel(self.other_commands_tab)
        self.label_4.setStyleSheet(_fromUtf8("font: 75 15pt \"Ubuntu\";"))
        self.label_4.setObjectName(_fromUtf8("label_4"))
        self.radio_module_settings_gridLayout.addWidget(self.label_4, 1, 0, 1, 1)
        self.enable_broadcasting_pushButton = QtGui.QPushButton(self.other_commands_tab)
        self.enable_broadcasting_pushButton.setObjectName(_fromUtf8("enable_broadcasting_pushButton"))
        self.radio_module_settings_gridLayout.addWidget(self.enable_broadcasting_pushButton, 0, 1, 1, 1)
        self.disable_broadcasting_pushButton = QtGui.QPushButton(self.other_commands_tab)
        self.disable_broadcasting_pushButton.setObjectName(_fromUtf8("disable_broadcasting_pushButton"))
        self.radio_module_settings_gridLayout.addWidget(self.disable_broadcasting_pushButton, 0, 2, 1, 1)
        self.toggle_transmission_label = QtGui.QLabel(self.other_commands_tab)
        self.toggle_transmission_label.setObjectName(_fromUtf8("toggle_transmission_label"))
        self.radio_module_settings_gridLayout.addWidget(self.toggle_transmission_label, 0, 0, 1, 1)
        self.transceiver_select_comboBox = QtGui.QComboBox(self.other_commands_tab)
        self.transceiver_select_comboBox.setObjectName(_fromUtf8("transceiver_select_comboBox"))
        self.transceiver_select_comboBox.addItem(_fromUtf8(""))
        self.transceiver_select_comboBox.addItem(_fromUtf8(""))
        self.radio_module_settings_gridLayout.addWidget(self.transceiver_select_comboBox, 2, 0, 1, 1)
        self.transceiver_select_pushButton = QtGui.QPushButton(self.other_commands_tab)
        self.transceiver_select_pushButton.setObjectName(_fromUtf8("transceiver_select_pushButton"))
        self.radio_module_settings_gridLayout.addWidget(self.transceiver_select_pushButton, 2, 1, 1, 1)
        self.formLayout.setLayout(0, QtGui.QFormLayout.LabelRole, self.radio_module_settings_gridLayout)
        self.gridLayout_4 = QtGui.QGridLayout()
        self.gridLayout_4.setObjectName(_fromUtf8("gridLayout_4"))
        self.formLayout.setLayout(2, QtGui.QFormLayout.LabelRole, self.gridLayout_4)
        self.gridLayout_3 = QtGui.QGridLayout()
        self.gridLayout_3.setObjectName(_fromUtf8("gridLayout_3"))
        self.formLayout.setLayout(3, QtGui.QFormLayout.LabelRole, self.gridLayout_3)
        self.separation_label = QtGui.QLabel(self.other_commands_tab)
        self.separation_label.setText(_fromUtf8(""))
        self.separation_label.setObjectName(_fromUtf8("separation_label"))
        self.formLayout.setWidget(4, QtGui.QFormLayout.LabelRole, self.separation_label)
        self.gridLayout_5 = QtGui.QGridLayout()
        self.gridLayout_5.setObjectName(_fromUtf8("gridLayout_5"))
        self.formLayout.setLayout(1, QtGui.QFormLayout.LabelRole, self.gridLayout_5)
        self.modes_of_operation_tabWidget.addTab(self.other_commands_tab, _fromUtf8(""))
        self.tab = QtGui.QWidget()
        self.tab.setObjectName(_fromUtf8("tab"))
        self.layoutWidget = QtGui.QWidget(self.tab)
        self.layoutWidget.setGeometry(QtCore.QRect(10, 10, 541, 61))
        self.layoutWidget.setObjectName(_fromUtf8("layoutWidget"))
        self.real_time_clock_settings_gridLayout = QtGui.QGridLayout(self.layoutWidget)
        self.real_time_clock_settings_gridLayout.setMargin(0)
        self.real_time_clock_settings_gridLayout.setObjectName(_fromUtf8("real_time_clock_settings_gridLayout"))
        self.set_real_time_pushButton = QtGui.QPushButton(self.layoutWidget)
        self.set_real_time_pushButton.setObjectName(_fromUtf8("set_real_time_pushButton"))
        self.real_time_clock_settings_gridLayout.addWidget(self.set_real_time_pushButton, 2, 1, 1, 1)
        self.set_real_time_date_TimeEdit = QtGui.QDateTimeEdit(self.layoutWidget)
        self.set_real_time_date_TimeEdit.setDateTime(QtCore.QDateTime(QtCore.QDate(2016, 1, 1), QtCore.QTime(0, 0, 0)))
        self.set_real_time_date_TimeEdit.setObjectName(_fromUtf8("set_real_time_date_TimeEdit"))
        self.real_time_clock_settings_gridLayout.addWidget(self.set_real_time_date_TimeEdit, 2, 0, 1, 1)
        self.other_commands_real_time_clock_settings_label = QtGui.QLabel(self.layoutWidget)
        self.other_commands_real_time_clock_settings_label.setStyleSheet(_fromUtf8("font: 75 15pt \"Ubuntu\";"))
        self.other_commands_real_time_clock_settings_label.setObjectName(_fromUtf8("other_commands_real_time_clock_settings_label"))
        self.real_time_clock_settings_gridLayout.addWidget(self.other_commands_real_time_clock_settings_label, 1, 0, 1, 1)
        self.modes_of_operation_tabWidget.addTab(self.tab, _fromUtf8(""))
        self.gridLayout_2.addWidget(self.modes_of_operation_tabWidget, 4, 0, 1, 1)
        self.undecoded_packages_textEdit = QtGui.QTextEdit(self.centralwidget)
        self.undecoded_packages_textEdit.setStyleSheet(_fromUtf8("background-color: qlineargradient(spread:reflect, x1:0.038, y1:0.517045, x2:1, y2:0.511, stop:0.402844 rgba(255, 255, 255, 254), stop:1 rgba(174, 151, 255, 255));"))
        self.undecoded_packages_textEdit.setObjectName(_fromUtf8("undecoded_packages_textEdit"))
        self.gridLayout_2.addWidget(self.undecoded_packages_textEdit, 1, 0, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)
        self.actionOpen = QtGui.QAction(MainWindow)
        self.actionOpen.setEnabled(True)
        self.actionOpen.setObjectName(_fromUtf8("actionOpen"))
        self.actionSave = QtGui.QAction(MainWindow)
        self.actionSave.setObjectName(_fromUtf8("actionSave"))
        self.actionClose = QtGui.QAction(MainWindow)
        self.actionClose.setObjectName(_fromUtf8("actionClose"))

        self.retranslateUi(MainWindow)
        self.modes_of_operation_tabWidget.setCurrentIndex(1)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(_translate("MainWindow", "Satellite simulator control program", None))
        self.execution_date_time_checkBox.setText(_translate("MainWindow", "Выполнить команду сразу при получении", None))
        self.execution_date_time_label.setText(_translate("MainWindow", "Установить время и дату выполнения посылаемой команды или выполнить команду сразу при получении:", None))
        self.undecoded_data_from_packages_label.setText(_translate("MainWindow", "Панель отображения содержимого ответных пакетов:", None))
        self.panel_for_manual_sending_of_commands_label.setText(_translate("MainWindow", "Панель посыла команд в ручном режиме:", None))
        self.enable_nominal_mode_pushButton.setText(_translate("MainWindow", "Отправить", None))
        self.enable_operating_mode_label.setText(_translate("MainWindow", "Перейти в режим работы с научной аппаратурой ", None))
        self.enable_operating_mode_pushButton.setText(_translate("MainWindow", "Отправить", None))
        self.enable_nominal_mode_label.setText(_translate("MainWindow", "Перейти в штатный режим работы", None))
        self.enable_minimal_mode_label.setText(_translate("MainWindow", "Перейти в режим работы с минимальным энергопотреблением ", None))
        self.enable_minimal_mode_pushButton.setText(_translate("MainWindow", "Отправить", None))
        self.modes_of_operation_tabWidget.setTabText(self.modes_of_operation_tabWidget.indexOf(self.modes_of_operation_tab), _translate("MainWindow", "Режимы работы", None))
        self.device_power_disable_pushButton.setText(_translate("MainWindow", " Выключить", None))
        self.label.setText(_translate("MainWindow", " Идентификатор оборудования:", None))
        self.device_power_enable_pushButton.setText(_translate("MainWindow", " Включить", None))
        self.label_2.setText(_translate("MainWindow", "Управление питанием:", None))
        self.label_3.setText(_translate("MainWindow", "Отправка команд:", None))
        self.label_5.setText(_translate("MainWindow", "Имя команды:", None))
        self.device_id_comboBox.setItemText(1, _translate("MainWindow", "power", None))
        self.device_id_comboBox.setItemText(2, _translate("MainWindow", "cpu_temp", None))
        self.device_id_comboBox.setItemText(3, _translate("MainWindow", "light", None))
        self.device_id_comboBox.setItemText(4, _translate("MainWindow", "hmc58831", None))
        self.device_id_comboBox.setItemText(5, _translate("MainWindow", "mpu6050", None))
        self.device_id_comboBox.setItemText(6, _translate("MainWindow", "ms5611", None))
        self.device_id_comboBox.setItemText(7, _translate("MainWindow", "ds1621", None))
        self.label_6.setText(_translate("MainWindow", "Аргумент команды:", None))
        self.device_command_pushButton.setText(_translate("MainWindow", "Выполнить", None))
        self.modes_of_operation_tabWidget.setTabText(self.modes_of_operation_tabWidget.indexOf(self.toggle_power_tab), _translate("MainWindow", "Исполнительные устройства", None))
        self.label_4.setText(_translate("MainWindow", "Выбор основного передатчика:", None))
        self.enable_broadcasting_pushButton.setText(_translate("MainWindow", "Включить", None))
        self.disable_broadcasting_pushButton.setText(_translate("MainWindow", "Выключить", None))
        self.toggle_transmission_label.setText(_translate("MainWindow", "Вещание в эфир", None))
        self.transceiver_select_comboBox.setItemText(0, _translate("MainWindow", "TNCA", None))
        self.transceiver_select_comboBox.setItemText(1, _translate("MainWindow", "TNCB", None))
        self.transceiver_select_pushButton.setText(_translate("MainWindow", "Назначить основным", None))
        self.modes_of_operation_tabWidget.setTabText(self.modes_of_operation_tabWidget.indexOf(self.other_commands_tab), _translate("MainWindow", "Радиомодуль", None))
        self.set_real_time_pushButton.setText(_translate("MainWindow", "Отправить", None))
        self.other_commands_real_time_clock_settings_label.setText(_translate("MainWindow", " Установка даты и времени на имитаторе СМКА:", None))
        self.modes_of_operation_tabWidget.setTabText(self.modes_of_operation_tabWidget.indexOf(self.tab), _translate("MainWindow", "Другие команды", None))
        self.actionOpen.setText(_translate("MainWindow", "Open", None))
        self.actionSave.setText(_translate("MainWindow", "Save", None))
        self.actionClose.setText(_translate("MainWindow", "Close", None))

